export const modelMap = {
    "meta-llama/Llama-3.3-70B-Instruct-Turbo": "Llama 3.3 70B Instruct Turbo",
    "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo": "Meta Llama 3.1 8B Instruct Turbo",
    "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo": "Meta Llama 3.1 70B Instruct Turbo",
    "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo": "Meta Llama 3.1 405B Instruct Turbo",
    "meta-llama/Meta-Llama-3-8B-Instruct-Turbo": "Meta Llama 3 8B Instruct Turbo",
    "meta-llama/Meta-Llama-3-70B-Instruct-Turbo": "Meta Llama 3 70B Instruct Turbo",
    "meta-llama/Llama-3.2-3B-Instruct-Turbo": "Llama 3.2 3B Instruct Turbo",
    "meta-llama/Meta-Llama-3-8B-Instruct-Lite": "Meta Llama 3 8B Instruct Lite",
    "meta-llama/Meta-Llama-3-70B-Instruct-Lite": "Meta Llama 3 70B Instruct Lite",
    "meta-llama/Llama-3-8b-chat-hf": "Llama 3 8B Chat HF",
    "meta-llama/Llama-3-70b-chat-hf": "Llama 3 70B Chat HF",
    "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF": "Llama 3.1 Nemotron 70B Instruct HF",
    "Qwen/Qwen2.5-Coder-32B-Instruct": "Qwen 2.5 Coder 32B Instruct",
    "Qwen/QwQ-32B-Preview": "Qwen QwQ 32B Preview",
    "microsoft/WizardLM-2-8x22B": "WizardLM 2 8x22B",
    "google/gemma-2-27b-it": "Gemma 2 27B IT",
    "google/gemma-2-9b-it": "Gemma 2 9B IT",
    "databricks/dbrx-instruct": "DBRX Instruct",
    "deepseek-ai/deepseek-llm-67b-chat": "DeepSeek LLM 67B Chat",
    "deepseek-ai/DeepSeek-V3": "DeepSeek V3",
    "google/gemma-2b-it": "Gemma 2B IT",
    "Gryphe/MythoMax-L2-13b": "MythoMax L2 13B",
    "meta-llama/Llama-2-13b-chat-hf": "Llama 2 13B Chat HF",
    "mistralai/Mistral-7B-Instruct-v0.1": "Mistral 7B Instruct v0.1",
    "mistralai/Mistral-7B-Instruct-v0.2": "Mistral 7B Instruct v0.2",
    "mistralai/Mistral-7B-Instruct-v0.3": "Mistral 7B Instruct v0.3",
    "mistralai/Mixtral-8x7B-Instruct-v0.1": "Mixtral 8x7B Instruct v0.1",
    "mistralai/Mixtral-8x22B-Instruct-v0.1": "Mixtral 8x22B Instruct v0.1",
    "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO": "Nous Hermes 2 Mixtral 8x7B DPO",
    "Qwen/Qwen2.5-7B-Instruct-Turbo": "Qwen 2.5 7B Instruct Turbo",
    "Qwen/Qwen2.5-72B-Instruct-Turbo": "Qwen 2.5 72B Instruct Turbo",
    "Qwen/Qwen2-72B-Instruct": "Qwen 2 72B Instruct",
    "upstage/SOLAR-10.7B-Instruct-v1.0": "SOLAR 10.7B Instruct v1.0",
} as const;
  
export type ModelKey = keyof typeof modelMap;
  